# Generated by Django 5.2.7 on 2025-10-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="post",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Изображение, отображаемое в списке постов или на главной странице блога.",
                null=True,
                upload_to="blog_previews/",
                verbose_name="Превью (изображение)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
