# Generated by Django 5.2.7 on 2025-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Если выключено — товар не виден в списке/детальной странице для обычных пользователей.",
                verbose_name="Опубликован",
            ),
        ),
    ]
