# Generated by Django 5.2.7 on 2025-11-02 21:54

from django.db import migrations
from django.conf import settings


def set_owner(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    User = apps.get_model(
        settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1]
    )

    # пробуем найти суперпользователя, иначе берем первого попавшегося пользователя
    owner = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if not owner:
        # если пользователей нет, оставляем как есть (потом не даст ужесточить поле — создайте пользователя)
        return

    Product.objects.filter(owner__isnull=True).update(owner=owner)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_owner"),
    ]

    operations = [
        migrations.RunPython(set_owner, migrations.RunPython.noop),
    ]
